baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ample"
theme = "ample"
googleAnalytics = ""
disqusShortname = "spork"
pygmentsCodeFences = true

# pygmentsCodeFencesGuessSyntax IS VERY BUGGY
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "solarized-dark"
#pygmentsOptions = "linenos=table"
pygmentsUseClasses = true
enableEmoji = true
footnoteReturnLinkContents = "↑"

paginate = 1

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
    description = "A minimal AMP-compatible Hugo website"
    post_navigation = true
    footer = "&copy; All rights reserved. Powered by [Hugo](https://gohugo.io/) and [Ample](https://github.com/yawpitchroll/ample)"

[params.ample]
    syntaxStyle = "" # default choices are "light" and "dark"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-square-solid"
    title = "Send an email"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "github-square-brands"
    title = "Connect on Github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter-square-brands"
    title = "Connect on Twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/user-name-a123456789/"
    name = "linkedin-brands"
    title = "Connect on LinkedIn"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/username/"
    name = "facebook-square-brands"
    title = "Connect on Facebook"
    weight = 5

[[menu.icon]]
    url = "https://www.reddit.com/user/username/"
    name = "reddit-square-brands"
    title = "Connect on Reddit"
    weight = 6
