## BASIC SITE CONFIGURATION
baseURL = "https://yawpitchroll.github.io/"
theme = "frugal"
defaultContentLanguage = "en"


## ANALYTICS CONFIGURATION
googleAnalytics = "UA-30240801-1"


## SYNTAX HIGHLIGHTING CONFIGURATION
pygmentsUseClasses = true                   # must be true; enabled Frugal syntax highlighting
pygmentsCodeFences = true                   # should be true; enables Github-style code fences
pygmentsCodeFencesGuessSyntax = false       # should be false; has never worked properly 
pygmentsStyle = ""                          # should be empty; Frugal ignores this setting
#pygmentsOptions = "linenos=table"          # uncomment if you ALWAYS want linenos


## DEMO SITE CONFIGURATION
paginate = 5
enableEmoji = true
footnoteReturnLinkContents = "↑"


## PRIVACY CONFIGURATION (https://gohugo.io/about/hugo-and-gdpr/)
[privacy.disqus]
    disable = false

[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[privacy.instagram]
    disable = false
    simple = true

[privacy.twitter]
    disable = false
    enableDNT = true
    simple = true

[privacy.vimeo]
    disable = false
    simple = true

[privacy.youtube]
    disable = false
    privacyEnhanced = true


## LANGUAGES CONFIGURATION
[languages.en]
    weight = 0
    languageName = "English"
    title = "yawpitchroll"
    copyright = "2019 Michael Morehouse"
    description = "The electronic home of Michael Morehouse; coder, VFX pipeline expert, sometimes world-weary adventurer, and narrowboat skipper."


## TAXONOMIES CONFIGURATION
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


## RELATED POSTS CONFIGURATION
[related]
    threshold = 80
    includeNewer = true
    toLower = true

[[related.indices]]
    name = "series"
    weight = 100

[[related.indices]]
    name = "keywords"
    weight = 80

[[related.indices]]
    name = "tags"
    weight = 60

[[related.indices]]
    name = "date"
    weight = 10


## NAVIGATION MENU CONFIGURATION
[[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 2


## THEME-SPECIFIC CONFIGURATION
[params.frugal.site]
    googleSiteVerificationID = "sBH5B-K8H5X_W-rkdiyd0K9FmhQLiqbEbGcrpEOUeTk"

[params.frugal.style]
    syntaxHighlightMode = "dark"                # choices are "light" and "dark", defaults to "light"
    accentColor = ""                            # defaults to "#0379C4" 

[params.frugal.pages.home]
    link = "posts"

[params.frugal.pages.e404]
    link = "posts"

[params.frugal.seo.facebook]
    appid = "169846159809380"
    admins = []

[params.frugal.author]
    name = "Michael Morehouse"
    email = "yawpitch@yawpitchroll.com"

[params.frugal.author.social]
    facebook = "yawpitch"
    github = "yawpitch"
    twitter = "yawpitchroll"
    linkedin = "yawpitchroll"
    reddit = "yawpitch"

[params.frugal.publisher]
    name = "yawpitchroll"
    
[params.frugal.publisher.social]
    facebook = ""                           # publisher sameAs links for Structured Data
    github = ""
    twitter = ""
    linkedin = ""
    reddit = ""

[params.frugal.formspree]
    email = "contact@yawpitchroll.com"      # enables the formspree "contact me" form

[params.frugal.mailchimp]
    server = "yawpitchroll.us20.list-manage.com"
    userid = "80b359475ddf7e0c8b943a7c3"
    audienceid = "90b062cd78"

## SOCIAL LINKS IN FOOTER
[[params.frugal.social.links]]
    name = "github"
    weight = 1

[[params.frugal.social.links]]
    name = "twitter"
    weight = 2

[[params.frugal.social.links]]
    name = "linkedin"
    weight = 3

[[params.frugal.social.links]]
    name = "reddit"
    weight = 4


## POST SOCIAL SHARING CONFIGURATION
[[params.frugal.social.share]]
    provider = "facebook"
    id = "169846159809380"
    weight = 1

[[params.frugal.social.share]]
    provider = "twitter"
    weight = 2
    
[[params.frugal.social.share]]
    provider = "linkedin"
    weight = 3

[[params.frugal.social.share]]
    provider = "whatsapp"
    weight = 4

